stages:
  - image
  - lint
  - test

variables:
  CODECOV_TOKEN: 4d2d8534-60ec-48b3-bf55-93b92f25913d

image: registry.heptapod.net:443/fluiddyn/fluidsim/ci/default:stable

# check_bug:
#   image: fluiddyn/python3-stable:lastest
#   script:
#     - pip index versions flit-core
#     - pip install requests
#     - python3.9 tmp_bug_unearth.py

# Build an image for the other tasks; this should be a scheduled job, as
# it is quite unnecessary to run on every invocation.
CI image:
  stage: image
  tags:
    - container-registry-push
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_BUILD_IMAGES == "1"'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - ""
  script:
    - |
      cat > /kaniko/.docker/config.json <<EOF
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
    - >
      /kaniko/executor --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile
      --single-snapshot
      --cleanup
      --destination registry.heptapod.net:443/fluiddyn/fluidsim/ci/$CI_COMMIT_HG_BRANCH:stable

validate_code:
  stage: lint
  needs:
    - job: "CI image"
      optional: true
  script:
    - nox -s validate_code

tests:
  stage: test
  needs:
    - job: "CI image"
      optional: true
  script:
    - tox -e py39-fft,codecov

test_without_fft_and_pythran:
  stage: test
  needs:
    - job: "CI image"
      optional: true
  script:
    - nox -s test_without_fft_and_pythran
