stages:
  - image
  - lint
  # - test
  # - publish

variables:
  CODECOV_TOKEN: 4d2d8534-60ec-48b3-bf55-93b92f25913d
  # OMPI_ALLOW_RUN_AS_ROOT: "1"
  # OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"

image: registry.heptapod.net:443/fluiddyn/fluidsim/ci/default:stable
# image: fluiddyn/python3-stable:lastest

# before_script:
#   - pip install -U pdm --user

# Build an image for the above tasks; this should be a scheduled job, as
# it is quite unnecessary to run on every invocation.
CI image:
  stage: image
  tags:
    - container-registry-push
  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "schedule"'
  #   - if: '$CI_BUILD_IMAGES == "1"'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - ""
  script:
    - |
      cat > /kaniko/.docker/config.json <<EOF
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
    - >
      /kaniko/executor --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile
      --single-snapshot
      --cleanup
      --destination registry.heptapod.net:443/fluiddyn/fluidsim/ci/$CI_COMMIT_HG_BRANCH:stable

# tests:
#   script:
#     - pip install -U tox tox-pdm --user
#     - tox -e py39,py39-fft,codecov

validate_code:
  stage: lint
  needs:
    - job: "CI image"
      optional: true
  script:
    - pip index versions flit-core
    - pip install requests
    - python3.9 tmp_bug_unearth.py

    # - rm -rf ../unearth
    # - git clone https://github.com/paugier/unearth.git ../unearth
    # - pip install -e ../unearth --user
    # - python3.9 -c "from unearth import PackageFinder as F; f = F(index_urls=['https://pypi.org/simple/']); print(list(f.find_all_packages('flit-core')))"

    - pdm install -G dev -v
    - pdm run make lint
    - pdm run make black_check